# Generated by Django 5.2.12 on 2026-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(verbose_name='Kullanıcı Sorusu')),
                ('ai_response', models.TextField(verbose_name='Yapay Zeka Cevabı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
            ],
            options={
                'verbose_name': 'Sohbet Geçmişi',
                'verbose_name_plural': 'Sohbet Geçmişleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
