# Generated by Django 5.2.12 on 2026-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcibademData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sayfa Başlığı')),
                ('url', models.URLField(unique=True, verbose_name='Sayfa Linki')),
                ('content', models.TextField(verbose_name='Sayfa İçeriği')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Çekilme Tarihi')),
            ],
            options={
                'verbose_name': 'Acıbadem Verisi',
                'verbose_name_plural': 'Acıbadem Verileri',
            },
        ),
    ]
